steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=asia-southeast2-docker.pkg.dev/freshcheck-c23-ps202f/gcloudapi/backendapi:dev'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/freshcheck-c23-ps202f/gcloudapi/backendapi:dev'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'backendapi'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/freshcheck-c23-ps202f/gcloudapi/backendapi:dev'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '2'
